repositories:
  - "https://mobb-pf.github.io/helm-repository"
  - git@github.com:redhat-blackbelt-online-boutique/online-boutique-cd.git

microenvironments:
  - name: ob
    requests:
      cpu: 30
      memory: 22Gi
    limits:
      cpu: 30
      memory: 22Gi
    projects:
      - name: sbox
        labels: |
          name: ob-sbox
          argocd.argoproj.io/managed-by: openshift-gitops

  - name: db
    requests:
      cpu: 2
      memory: 3Gi
    limits:
      cpu: 2
      memory: 3Gi
    projects:
      - name: sbox
        labels: |
          name: db-sbox
        microservices:
          - name: mssql-payments
            gitRepo: git@github.com:redhat-blackbelt-online-boutique/online-boutique-cd.git
            branch: sbox-app-mssql
            helmRepo: "https://mobb-pf.github.io/helm-repository"
            chartName: mssql-linux
            chartVersion: 0.2.0



 